language: python

python: 3.6

dist: bionic

services:
    - docker

cache: pip

before_install:
    - |
      if [ "$SERVER" == "true" ]; then
        cd src/server
        pip install -r dev-requirements.txt
        pip install -e .
        cd ../clients/python
        pip install -r dev-requirements.txt
        pip install -e .
        cd ../../..
      fi
    - |
      if [ "$SKIP_SERVER_INSTALL" != "true" ]; then
        docker-compose -f .travis-docker-compose.yml up -d
        cd src/server
        pip install -r requirements.txt
        cd ../..
      fi
    - |
      if [ "$TEST_CLIENT" == "true" ]; then
        cd src/clients/python
        pip install -r requirements.txt
        cd ../../server
        honcho start
        cd ../../
      fi
      

jobs:
    include:
      - name: "lint"
        script: cd src/server && flake8 && cd ../clients/python && flake8 && cd ../../../tests/server && flake8 && cd ../clients/python && flake8
        env:
          - SERVER=true
          - SKIP_SERVER_INSTALL=true
      - name: "server-unit"
        script: pytest tests/server --disable-pytest-warnings
        env:
          - SERVER=true
      - name: "clients-unit"
        script: pytest tests/clients --disable-pytest-warnings
        env:
          - SERVER=true
          - TEST_CLIENT=true
